# Generated by Django 5.1.3 on 2024-11-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=255)),
                ('tuition_fee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
